### ISSUE TITLE
Figure granularity when time_interval is in years

### ISSUE THREAD

**Issue by AlexSundermann** [nstrayer/timelinePlot#1]
When we toggle between different specifications for time_interval ("days", "weeks", "years") the way the package interprets the interval_width changes accordingly. Therefore the definition of the graph changes even if the user only wishes to change the way time appears on the x-axis. This is fine except for it appears that the code can’t deal with interval widths of less than 1 unit, so when years are the time_interval, the distribution appears super chunky. Here is an example with the SCCS data.  

This is when time_interval="years" and interval_width is not specified: 
![image](https://cloud.githubusercontent.com/assets/22453025/18842129/a9f29e3e-83d9-11e6-83cf-1aab0ddbbbd4.png)

This is when time_interval="years" and interval_width=0.001
![image](https://cloud.githubusercontent.com/assets/22453025/18842166/c99aed54-83d9-11e6-9464-0005759bcdfe.png)

time_interval="years" and interval_width=0.5 
![image](https://cloud.githubusercontent.com/assets/22453025/18842200/eb0f412e-83d9-11e6-8e51-afd0f125ef86.png)

time_interval="years" and interval_width=1
![image](https://cloud.githubusercontent.com/assets/22453025/18842160/c534ace6-83d9-11e6-84fa-1f19459af89f.png)

When I start to increase interval_width>1, the graph starts to become chunkier: 
time_interval="years" and interval_width=5
![image](https://cloud.githubusercontent.com/assets/22453025/18842249/0461bdc8-83da-11e6-963f-ac5a960dfb18.png)

I anticipate that this will be a problem when an authors wishes to demonstrate study events in terms of years, but wants to achieve higher definition in the distribution of event timing

**Comment by nstrayer** [comment]
Fixed it! 

Problem was with a `max` command that never let the interval width drop below one. Has been remedied.
