### ISSUE TITLE
Custom breaks error

### ISSUE THREAD

**Issue by AlexSundermann** [nstrayer/timelinePlot#2]
When I try to include custom breaks in a study that ranges from 0-12 years with the line : `custom_xbreaks = c(0, 5, 10)` 

I get the following error message. 
`In addition: Warning messages:
1: In bind_rows_(x, .id) :
  binding factor and character vector, coercing into character vector
2: In if (is.na(event_labels)) event_labels = sort(event_vars) :
  the condition has length > 1 and only the first element will be used`

I get the error message even when I use the default time_interval of days.
`custom_xbreaks = c(0, 1825, 3650)` 

(In all my attempts, I have ensured that my requested custom breaks fall within the represented time range).

**Comment by nstrayer** [comment]
I think perhaps you missed the actual error message here. I am assuming it was this though?

``` r
> timelinePlot(d, event_vars = c("gestage", "congestftlmp", "congest6wklmp", "SABlmp","lblmp"),time_interval = "day", 
+              custom_xbreaks = c(100, 250, 420))
Error in if (is.na(event_labels)) event_labels = sort(event_vars) : 
  argument is of length zero
In addition: Warning messages:
1: In bind_rows_(x, .id) :
  binding factor and character vector, coercing into character vector
2: In is.na(event_labels) :
  is.na() applied to non-(list or vector) of type 'NULL'
```

**Comment by nstrayer** [comment]
The following command now works. 

``` r
> timelinePlot(d, event_vars = c("gestage", "congestftlmp", "congest6wklmp", "SABlmp","lblmp"),time_interval = "day", 
+              custom_xbreaks = c(100, 250, 420))
```

The problem was on the lines  

``` r
     if(length(custom_xlabs) != length(custom_xbreaks)){
       stop("Your labels must be the same length as your breaks.")
     }
```

This will throw an error if you have custom breaks defined but no custom labels. Just took it out because ggplot already spits an informative error for this.
